apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadjob
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loadjob
  template:
    metadata:
      labels:
        app: loadjob
    spec:
      containers:
      - name: loadjob
        image: cuestio/loadjob:v0.1
        resources:
          limits:
            cpu: 1000m
            memory: 500Mi
        env:
        - name: Duration
          value: "180" # seconds
        - name: CPULimit
          value: "1000" # millicores
        - name: RAMLimit
          value: "500" # Mib
        - name: ExitCode
          value: "0" # 0 - success, otherwise error
      nodeSelector:
        type: cuest-node
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: "Equal"
        value: "cuest"
        effect: NoSchedule
