apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadjob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadjob
  template:
    metadata:
      labels:
        app: loadjob
    spec:
      containers:
      - name: loadjob
        image: srostyslav/loadjob:v0.0.3
        env:
        - name: Duration
          value: "180" # refers to the running interval of the service, measured in seconds. After the specified duration has elapsed, the service will exit. (default 180 seconds)
        - name: CPUSleep
          value: "10000" # measured in nanoseconds, controls the CPU load of the service. If it is not specified, the service will utilize 100% of the CPU.
        - name: RAM
          value: "20" # refers to the amount of memory, measured in megabytes, that you want to allocate for the service.
        - name: ExitCode
          value: "1" # the code that the service will return upon completion (0 for success, and any other value indicating an error).