name: Cuest Use Cases CI
on:
  pull_request:
    branches:
      - "main"

jobs:
        
  LoadJob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: /loadjob/Dockerfile
          push: true
          tags: use-cases/loadjob:latest
        
