name: Cuest Use Cases CI
on:
  pull_request:
    branches:
      - "main"

jobs:
        
  LoadJob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: docker build -t use-cases/loadjob:latest -f ./loadjos/Dockerfile ./loadjob/
        
